Добавлена функциональность создания счёта (фронт)
gpb-it-factory/khasmamedov-telergam-bot pull request #24
Opened 2024-06-17 10:21 UTC by timk01

https://github.com/gpb-it-factory/khasmamedov-telergam-bot/issues/19

2024-06-17 11:52 UTC, timk01 commented
@vaganov-vadim Вадим, помоги пожалуйста - я запутался с мердж-конфликтом, я же не могу мейн (транк) никуда пушить (там откатывал изменения с `git reset hard1` два раза), соответственно я подтягиваю изменения из мейна как сказано здесь
- примердже пишет ап ту дейт + пишет конфликтов нет на пуш (сморти скрины). 
А гитхаб пишет конфликты... чушь какая-то
![изображение](https://github.com/gpb-it-factory/khasmamedov-telergam-bot/assets/25296074/1d853cd6-dd38-4deb-98ca-a3744d4e968b)
![изображение](https://github.com/gpb-it-factory/khasmamedov-telergam-bot/assets/25296074/7735af97-ae0d-4556-838a-e1e6547bea50)

2024-06-17 16:55 UTC, timk01 commented
А теперь что еще более важно. Следующее. У меня сейчас реквест уже аккаунта = фактически реквест юзера + название аккаунта.
Поэтому что уже на миддле я делаю в контроллере запрос в серсис - сначала на регу, и если ответ: уже есть//новый юзер - это ОК и тогда я делаю запрос на создание аккаунта (по той же логике). Если ошибка - сразу возвращаю ошибку.

Верно ли это ?

2024-06-17 20:36 UTC, timk01 commented
https://github.com/gpb-it-factory/khasmamedov-middle-service/issues/9
если что, миддл-слой.

2024-06-18 21:13 UTC, timk01 commented
Конфликт разрешен, большую чатсь изменений удалось успешно сохранить (в-основном кое-где остался не слишком верный нейминг, кое-где местами минорно измнена логика, но это малозначительные изменения и они ни на что не влияют) и откатить.

Сверял с этим коммитом 3b64d7d40945a1a979520779199d43948e9bd17b, вручную. 

**Тесты заводятся.**

Большая часть уже ВЕРНЫХ изменений здесь со значительно большим количеством тестов (теперь покрытие 70-75%, и это без взаимодействия с ТГ, но это тестировать я не буду) здесь:
https://github.com/gpb-it-factory/khasmamedov-telergam-bot/pull/25
Но это уже с получением данных аккаунта.

2024-06-20 14:09 UTC, timk01 commented
@vaganov-vadim https://github.com/gpb-it-factory/khasmamedov-telergam-bot/pull/25
этот и текущий https://github.com/gpb-it-factory/khasmamedov-telergam-bot/pull/24 если времени вообще 0, может попросить других проверяющих уже сейчас начинать смотреть, чтобы паралелльно шли проверки сервисов А и Б 
(потому что я назначал тебя сам тут)

2024-06-22 19:44 UTC, vaganov-vadim requested changes
Привет! Реализация хорошая. Оставил пару комментов по улучшениям. Посмотри, пожалуйста.

2024-06-22 19:44 UTC, vaganov-vadim commented on src/test/java/ru/gpb/app/service/RegistrationServiceTest.java
> +    public void registerResponseInvokedGeneralException() {
Не совсем по теме PR, но по тестам надо разобраться. Проверяем поведение, а не внутрянку. Ну и как я говорил, если есть verify - в 99% случаев это знание внутренней логики и проверка не совсем того.

2024-06-22 19:44 UTC, vaganov-vadim commented on src/test/java/ru/gpb/app/service/AccountServiceTest.java
> +        when(restTemplate.postForEntity(url, accountRequest, Void.class))
Над рест-темплейтом лучше сделать какой-то класс-обёртку, например, какой-то Client (лучше вообще под интерфейсом), тогда не придётся мокать рест-темплейт, можно свою реализацию подсунуть.

2024-06-22 19:44 UTC, vaganov-vadim commented on src/test/java/ru/gpb/app/handler/CreateAccountCommandTest.java
> +        assertThat("/createaccount").isEqualTo(result);
Ну такое себе, проверяем сами себя =) Мне кажется, что особо и нет смысла это проверять, лучше такое на верхнем уровне как-то проверить.

2024-06-22 19:44 UTC, vaganov-vadim commented on src/test/java/ru/gpb/app/handler/CreateAccountCommandTest.java
> +        Message mockedMessage = mock(Message.class);
Нельзя создать руками Message и User? Мне кажется, нет смысла прибегать к мокам.

2024-06-22 19:44 UTC, vaganov-vadim commented on src/main/java/ru/gpb/app/service/AccountService.java
> +        } catch (HttpStatusCodeException e) {
Мне кажется, что лучше этим обернуть только сам вызов, а не весь код В общем, здесь можно немного поиграться со вложенностью, но это не очень критично, просто как наблюдение.

2024-06-22 19:44 UTC, vaganov-vadim commented on src/main/java/ru/gpb/app/handler/CreateAccountCommand.java
> +    public boolean needsServiceInteraction() {
А для чего этот флажок?

2024-06-23 09:28 UTC, timk01 commented on src/test/java/ru/gpb/app/service/RegistrationServiceTest.java
> +    public void registerResponseInvokedGeneralException() {
Там везде verify...
Или его можно не ставить вовсе, но непонятно когда его не ставить, а когда - он нужен. 
Предлагаешь везде убрать ? Логика-то несложная.

2024-06-23 09:55 UTC, timk01 commented on src/test/java/ru/gpb/app/service/RegistrationServiceTest.java
> +    public void registerResponseInvokedGeneralException() {
https://kevinmhickey.com/2018/01/02/why-i-avoid-using-verify-in-tests/

Если это то, выпиливать ?) Неясно тогда когда оно реально нужно.

2024-06-23 10:53 UTC, timk01 commented on src/test/java/ru/gpb/app/service/AccountServiceTest.java
> +        when(restTemplate.postForEntity(url, accountRequest, Void.class))
Это примерно то же, о чем Андрей Бирюков говорил в ревью на миддл. Принял. 

Проблема лишь в том, что это понятно, но в голову помещается пока с трудом :(

2024-06-23 13:47 UTC, timk01 commented on src/test/java/ru/gpb/app/handler/CreateAccountCommandTest.java
> +        assertThat("/createaccount").isEqualTo(result);
Добавил registerUserCommand и creteAccountCommand в слой выше уже как интеграционную, думаю что все же стоит здесь их оставить, т.к. тесты простые и проверяют простую же логику и никому не мешают (например, мало ли описались или буковицу воткнули русскую - и тогда тест не пройдет проверку). Лишние ? Не думаю.

2024-06-23 13:52 UTC, timk01 commented on src/test/java/ru/gpb/app/handler/CreateAccountCommandTest.java
> +        assertThat("/createaccount").isEqualTo(result);
А вот кстати команды "пустые" типа пинг-понга, уже можно и повыпиливать с тестами - они не несут смысловой наргузки более. Как счиатешь ?

2024-06-23 13:54 UTC, timk01 commented on src/main/java/ru/gpb/app/handler/CreateAccountCommand.java
> +    public boolean needsServiceInteraction() {
Я там где-то писал логику работы, но суть в том, что это как маркерный метод, контролирует нужно ли взаимодействие дальше и заставляет программиста немного думать, соблюдая контракт.

Если я удаляю пустые команды - точно не нужен. Но если у нас например будет необходимость простого взаимодействия - снова понадобится.

2024-06-23 14:20 UTC, timk01 commented on src/test/java/ru/gpb/app/handler/CreateAccountCommandTest.java
> +        Message mockedMessage = mock(Message.class);
Если мы про что-то такое, у ТГ - нет сеттера. Только моками.
```
       message = new Message();
        message.setChat(123L);
        message.setFrom(user);
```
Юзера отдельно создал.

2024-06-23 14:54 UTC, timk01 commented on src/main/java/ru/gpb/app/service/AccountService.java
> +        } catch (HttpStatusCodeException e) {
![изображение](https://github.com/gpb-it-factory/khasmamedov-telergam-bot/assets/25296074/539c906a-2659-423b-a1ed-d7b492022477)

только если это ты имел в виду...

2024-06-23 15:08 UTC, timk01 commented
@vaganov-vadim Готово.

2024-06-25 16:31 UTC, vaganov-vadim commented on src/test/java/ru/gpb/app/service/RegistrationServiceTest.java
> +    public void registerResponseInvokedGeneralException() {
Они нужны в основном для проверки сайд-эффектов. Я приводил пример - например, отправка письма клиенту на почту, по сути мы можем проверить только факт отправки письма, но не можем проверить письмо в почте у клиента, в таком случае применимо.

2024-06-25 16:38 UTC, vaganov-vadim commented on src/test/java/ru/gpb/app/handler/CreateAccountCommandTest.java
> +        assertThat("/createaccount").isEqualTo(result);
А какую логику они проверяют? Что мы написал /createaccount там, где и должны были его написать?) Валидно только если не можем как-то более комплексно проверить.

2024-06-25 16:38 UTC, vaganov-vadim commented on src/test/java/ru/gpb/app/handler/CreateAccountCommandTest.java
> +        assertThat("/createaccount").isEqualTo(result);
ping/pong можно удалять, я думаю.

2024-06-25 16:39 UTC, vaganov-vadim commented on src/test/java/ru/gpb/app/handler/CreateAccountCommandTest.java
> +        Message mockedMessage = mock(Message.class);
Ок.

2024-06-25 16:39 UTC, vaganov-vadim commented on src/main/java/ru/gpb/app/service/AccountService.java
> +        } catch (HttpStatusCodeException e) {
Вроде того, да.

2024-06-25 16:40 UTC, vaganov-vadim commented on src/main/java/ru/gpb/app/handler/CreateAccountCommand.java
> +    public boolean needsServiceInteraction() {
Пока что не вижу в этом необходимости, т. к. неясно, как это влияет на контракт - в логике команды разраб может написать что угодно.

2024-06-25 16:41 UTC, vaganov-vadim approved these changes
Добавил комменты. Они неблокирующие, можешь обработать по желанию :) Аппрув.

2024-06-25 18:39 UTC, timk01 commented
Комментарии все записал, в 24 или 26 реквесте (скорее 26, он финальный) - учту. Спасибо. Сливаю.

2024-06-25 18:44 UTC, merged