Задание 2. Добавлен README
gpb-it-factory/khasmamedov-telergam-bot pull request #5
Opened 2024-05-06 20:24 UTC by timk01

В процессе произошел небольшой (или большой) хаос с ветками :(

2024-05-07 14:38 UTC, vaganov-vadim commented
Давай договоримся, что в рамках issue публикуется только код, который к нему относится. Иначе тяжело будет проверять PR и сессии ревью и исправлений будут дольше. По сути добавить gradle лучше под отдельный созданный тобой issue, сейчас блочить не буду, но придётся исправлять то что найду по gradle :)

2024-05-07 14:49 UTC, vaganov-vadim requested changes
В целом хорошо, много всяких интересных штук в README, но нужно отработать комментарии.

2024-05-07 14:49 UTC, vaganov-vadim commented on CHANGELOG.md
> +# Changelog
Не уверен, что он нужен, по идее это заменяет функциональность Releases в github.

2024-05-07 14:49 UTC, vaganov-vadim commented on README.md
> +
А великий addons/img.png для чего?)

2024-05-07 14:49 UTC, vaganov-vadim commented on src/main/resources/application.properties
> +spring.application.name=demo
Наверное проще, чтобы совпадало с именем проекта.

2024-05-07 14:49 UTC, vaganov-vadim commented on README.md
> +activate Клиент
activate Клиент лишнее, оно по сути и так есть скоуп всей цепочки.

2024-05-07 14:49 UTC, vaganov-vadim commented on README.md
> +((пока пусто))
Ну так-то у тебя уже Spring Boot приложение есть, заполняй эту секцию :)

2024-05-07 20:35 UTC, timk01 commented
Если есть желание, то может проще и разнести.
- так наверное и сделаю. благо, там не так много делать, вроде бы.

Остальное по комментариям - завтра. Только приехал.

2024-05-08 08:33 UTC, timk01 commented on CHANGELOG.md
> +# Changelog
https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases
- удалил, но штука тяжелая для понимания пока - чуть позже потыкаю еще.

2024-05-13 14:48 UTC, timk01 commented
Хочется постепенно начать задание №3 делать (с ботом), а я так понимаю что иного пути как копировать параллельно и копипастить потом из проекта в проект (или ветку, что наименее безболезненно) нет ?

2024-05-13 16:19 UTC, vaganov-vadim commented
По поводу продолжения по практике - можно отбранчиться от этой ветки. Но я сейчас сделаю ревью.

2024-05-13 16:38 UTC, vaganov-vadim commented on README.md
> +activate Клиент
По сути запросом клиента всё начинается и заканчивается, нет смысла отрисовывать под это отдельную область.

2024-05-13 16:40 UTC, vaganov-vadim approved these changes

2024-05-13 16:44 UTC, merged