Задание 3. Создан "скелет" бота
gpb-it-factory/khasmamedov-telergam-bot pull request #9
Opened 2024-05-18 19:04 UTC by timk01

В соответствии с [(https://github.com/gpb-it-factory/khasmamedov-telergam-bot/issues/8)]
Пока - сильно урезанная черновая версия, с базовым функционалом

2024-05-20 07:40 UTC, vaganov-vadim commented on src/main/java/ru/gpb/app/handler/OutcomingHandlerImpl.java
> +    private final Map<String, String> messageMap = new HashMap<>();
Нравится применение мапы здесь. Правда, что если команда будет не только строчку возвращать, а что-то делать? :)

2024-05-20 07:41 UTC, vaganov-vadim commented on src/main/java/ru/gpb/app/handler/OutcomingHandlerImpl.java
> +                .text(
Форматирование это вкусовщина, но тебе нравится когда вот так?)

2024-05-20 07:42 UTC, vaganov-vadim commented on src/main/java/ru/gpb/app/handler/OutcomingHandlerImpl.java
> +        messageMap.put("/ping", "pong");
Может, прокидывать заполненную мапу параметром? Будет проще тестировать, сейчас у тебя завязка на конкретную реализацию с конкретным наполнением.

2024-05-20 10:27 UTC, timk01 commented on build.gradle
> +	testCompileOnly 'org.projectlombok:lombok:1.18.32'
То, что я нашел - они так не включаются в артефакт. Сделано для этого.
Но я гуглил и особенно не вникал, у меня была задача заставить работать шайтан-машину.
Можно, по идее проще:
implementation 'org.projectlombok:lombok:1.18.32'
annotationProcessor 'org.projectlombok:lombok:1.18.32'

Но:
![изображение](https://github.com/gpb-it-factory/khasmamedov-telergam-bot/assets/25296074/07272903-7a63-43d8-8b3d-f10d2d76696f)

2024-05-20 10:29 UTC, timk01 commented on build.gradle
> +	testCompileOnly 'org.projectlombok:lombok:1.18.32'
![изображение](https://github.com/gpb-it-factory/khasmamedov-telergam-bot/assets/25296074/c3e3d1ee-89f9-40e2-8a9b-a9136a876f77)

Предлагаю оставить как есть.

2024-05-20 10:35 UTC, timk01 commented on src/main/java/ru/gpb/app/handler/OutcomingHandlerImpl.java
> +                .text(
![изображение](https://github.com/gpb-it-factory/khasmamedov-telergam-bot/assets/25296074/664a66be-8d48-40b5-80d1-a82862426a3a)

Можно так, я просто привык так делать. Здесь особой разницы нет - главное чтобы точечки на новую строку переносились. Давай сделаем как выше, я не против. 

Но когда код будет менее читаем (когда его много, читай) - точно надо выносить как отдельные слова.

2024-05-20 10:44 UTC, timk01 commented on src/main/java/ru/gpb/app/handler/OutcomingHandlerImpl.java
> +    private final Map<String, String> messageMap = new HashMap<>();
Как вариант, интерфейс комманд с методом `Execute ` -> `<String, Command>`, куда можно воткнуть свою реализацию команды (сейчас это чисто возврат текста), можно будет подумать ExecuteText, ExecuteSmth etc.

2024-05-20 10:47 UTC, timk01 commented on src/main/java/ru/gpb/app/handler/OutcomingHandlerImpl.java
> +        messageMap.put("/ping", "pong");
Раснести, добавив бин как конфиг ? Вариант вполне. Я посмотрел видосы всякие, статьи - мне показалось сложно. Сделал проще.
Переделаю через час-два - скину. Это и выше.

2024-05-20 15:48 UTC, timk01 commented on src/main/java/ru/gpb/app/handler/OutcomingHandlerImpl.java
> +        messageMap.put("/ping", "pong");
Посмотри - особое внимание на выделенный участок кода - ты это имел в виду ? В целом в констркутор можно добавить кучу таких разных мап - одна например будет за возврат Комманд отвечать, а Комманды могут быть разные - одна текст, вторая что еще... 
Ну, и добавим их в конструктор. Вроде бы гибко.

![изображение](https://github.com/gpb-it-factory/khasmamedov-telergam-bot/assets/25296074/5f0c8847-8c76-4d95-b8c9-9e3502eea1e3)

2024-05-22 17:17 UTC, vaganov-vadim commented on build.gradle
> +	testCompileOnly 'org.projectlombok:lombok:1.18.32'
Не, я не про compileOnly, я про testCompileOnly. Оно по идее от compileOnly должно и в тесты прокинуться. Могу быть не прав, поэтому это совсем не критично.

2024-05-22 17:22 UTC, vaganov-vadim requested changes
Добавил мыслей по улучшениям. Ты молодец, код с каждым разом становится всё лучше. Так держать!

2024-05-22 17:22 UTC, vaganov-vadim commented on src/main/java/ru/gpb/app/handler/HelpCommandImpl.java
> +public class HelpCommandImpl implements Command {
Я бы тут убрал Impl в названии, в целом нет необходимости всегда имплементации именно так называть, только если название имплементации совпадает с интерфейсом и надо как-то выделить.

2024-05-22 17:22 UTC, vaganov-vadim commented on src/main/java/ru/gpb/app/handler/Command.java
> +public interface Command {
Круто, что применил этот паттерн, мне нравится.

2024-05-22 17:22 UTC, vaganov-vadim commented on src/main/java/ru/gpb/app/config/Commandeer.java
> +        messageMap.put("/ping", new PingCommandImpl());
Хм, а есть ли вариант не составлять такую ассоциацию отдельно, а инкапсулировать названия команд прямо в класс команды? Тогда на уровне спринга мы просто будем получать список команд, которые есть в контексте (или которые мы зарегистрировали), а не добавлять их в мапу под конкретную строку. Как думаешь?

2024-05-22 17:22 UTC, vaganov-vadim commented on src/main/java/ru/gpb/app/handler/OutcomingHandlerImpl.java
> +public class OutcomingHandlerImpl implements OutcomingHandler {
Вот тут Impl норм :)

2024-05-22 17:22 UTC, vaganov-vadim commented on src/main/java/ru/gpb/app/handler/OutcomingHandlerImpl.java
> +    private final Map<String, String> messageMap = new HashMap<>();
Мысль отличная. Вижу, что так и сделал.

2024-05-22 17:22 UTC, vaganov-vadim commented on src/main/java/ru/gpb/app/handler/OutcomingHandlerImpl.java
> +        messageMap.put("/ping", "pong");
Да, я это имел в виду, здорово.

2024-05-22 18:07 UTC, timk01 commented on build.gradle
> +	testCompileOnly 'org.projectlombok:lombok:1.18.32'
Совсем не понял почему комментарии из другой ветки появились здесь. Ну, ладно.

`Оно по идее от compileOnly должно и в тесты прокинуться` - видимо все же не так.

2024-05-22 22:00 UTC, timk01 commented on src/main/java/ru/gpb/app/config/Commandeer.java
> +        messageMap.put("/ping", new PingCommandImpl());
Вариант есть, я даже понял суть как сделать, но вот незадача - он пока не видит бины, а я бьюсь над проблемой 5 час...

Завтра с утра поковыряю.

2024-05-23 07:06 UTC, timk01 commented on src/main/java/ru/gpb/app/config/Commandeer.java
> +        messageMap.put("/ping", new PingCommandImpl());
Это было непросто, но вроде победил.

2024-05-26 22:40 UTC, timk01 commented
@vaganov-vadim lgtm ? вливаю ?

2024-05-28 06:02 UTC, vaganov-vadim commented
@timk01 сегодня посмотрю. Тяжеловато готовить лекцию и быстро проводить ревью :)

2024-05-29 07:44 UTC, timk01 commented
@vaganov-vadim придется пинговать

2024-05-31 06:04 UTC, vaganov-vadim approved these changes
Удали закомментированный код и можно вливать. В целом всё хорошо, но отметил ещё момент для будущих улучшений.

2024-05-31 06:04 UTC, vaganov-vadim commented on src/main/java/ru/gpb/app/handler/Command.java
> +    //String sendTextAnswer();
Какой-то мусор остался.

2024-05-31 06:04 UTC, vaganov-vadim commented on src/main/java/ru/gpb/app/config/Commandeer.java
> +    public Map<String, Command> commandMsg() {
Как вариант для улучшения - можно вне этого PR. Есть ли смысл всё это оборачивать так, если можно просто заинжектить Set<Command> и всё?)

2024-06-02 10:14 UTC, timk01 commented on src/main/java/ru/gpb/app/config/Commandeer.java
> +    public Map<String, Command> commandMsg() {
Такой план мне понятен. Думаю, оставим пока. В туду/ту-финк-оф занесу.

2024-06-02 10:24 UTC, timk01 commented
@vaganov-vadim похоже требуется конфирм.

2024-06-03 05:29 UTC, vaganov-vadim approved these changes

2024-06-03 05:30 UTC, merged